### ISSUE TITLE
Planned release?

### ISSUE THREAD

**Issue by splattael** [jnbt/linr#2]
Hi Jonas,

are you planning to release `linr` any time soon?

On Ruby 2.4.x we see the following :warning: warning:

```
gems/linr-0.0.2/lib/linr/encoder/line.rb:59:    warning: constant ::Fixnum is deprecated
```

It's already fixed on `master` though :sunglasses: 

Thanks and kind regards,
  Peter

**Comment by jnbt** [comment]
0.0.3 published 🚢 

I'm thinking about releasing `1.0.0`. What is your opinion on this? We're using it now for some time in production....

**Comment by splattael** [comment]
Yay, thank you for releasing `0.0.3` :+1: :tada: 

About `1.0`: Yes, :shipit: :purple_heart:
